##Only used with Activate command.  Needs extensive documentation.

card_list = {
    'Energy Boosted Majin Buu': {draw: (me.piles["Deck"], False, 1)},
    'Vegeta, Prince of Speed': {draw: (me.piles["Deck"], False, 2)},
    'Bundle of Curiosity Son Goku': {draw: (me.piles["Deck"], False, 1)},
    'Vegito, Here to Save the Day': {draw: (me.piles["Deck"], False, 2)},
    'Saiyan Cabba': {draw: (me.piles["Life"], False, 1)},
    'Rising Fist Super Saiyan 2 Son Goku' : {draw: (me.piles["Deck"], False, 2)},
    'Reliable Trunks': {draw: (me.piles["Deck"], False, 1)},
    'Youthful Bulma': {draw: (me.piles["Deck"], False, 1)},
    'Unyielding Justice SS2 Trunks': {draw: (me.piles["Deck"], False, 1)},
    'Furious Rush Super Saiyan 3 Son Goku': {draw: (me.piles["Deck"], False, 1)},
    'Power Charge Bardock': {draw: (me.piles["Deck"], False, 1)},
    'Sister Attack Saiyan Kale': {draw: (me.piles["Deck"], False, 1)},
    'Sister Attack Saiyan Caulifla': {draw: (me.piles["Life"], False, 1)},
    'Super Reaction Narirama': {draw: (me.piles["Life"], False, 1)},
    'Triple Flash SS4 Son Goku': {draw: (me.piles["Deck"], False, 2)},
    'Daily Training Vegeta': {draw: (me.piles["Deck"], False, 1)},
    'Intensifying Power Trunks': {draw: (me.piles["Life"], False, 1)},
    'Dependable Mom Bulma': {draw: (me.piles["Deck"], False, 1)},
    'Saiyan Onslaught Kefla': {draw: (me.piles["Deck"], False, 1)},
    'Hoi, Emissary of Flame': {draw: (me.piles["Deck"], False, 2)},
    'Newfound Power Son Gohan': {draw: (me.piles["Life"], False, 1)},
    'Nail, the Namekian Ace': {draw: (me.piles["Deck"], False, 1)},
    'Kami, the Watcher': {draw: (me.piles["Deck"], False, 1)},
    'Bardock, the Progenitor': {draw: (me.piles["Life"], False, 1)},
    'Discovered Dynasty Son Gohan': {draw: (me.piles["Deck"], False, 2)},
    'Caring Mother Videl': {draw: (me.piles["Deck"], False, 1)},
    'Time Control Chronoa': {draw: (me.piles["Deck"], False, 1)},
    'Awe-Inspiring Intimidator SSB Vegito': {draw: (me.piles["Deck"], False, 1)},
    'Toppo Unleashed': {draw: (me.piles["Deck"], False, 2)},

    #mill section
    'Shun Shun, Protector Majin': {mill: (me.piles["Deck"], True, 2)},
    'Haru Haru, Attacker Majin': {mill: (me.piles["Deck"], True, 2)},
    'The Masked Saiyan': {mill: (me.piles["Deck"], True, 3)},
    'Hidden Darkness Tapion': {mill: (me.piles["Deck"], True, 3)},
    'Popo, Guardian\'s Aide': {mill: (me.piles["Deck"], True, 3)},
    'Gine, Here to Support': {mill: (me.piles["Deck"], True, 3)},
    'Putine, in Demigra\'s Thrall': {mill: (me.piles["Deck"], True, 2)},

    #burst section
    'Yamcha': {mill: (me.piles["Deck"], False, 2), draw: (me.piles["Deck"], False, 1)},
    'Yamcha, at 100 Percent': {mill: (me.piles["Deck"], False, 5)},
    'Janemba': {mill: (me.piles["Deck"], False, 2), draw: (me.piles["Deck"], False, 1)},
##    'Ghost Rampage SS Gotenks': {mill: (me.piles["Deck"], False, 2), draw: (me.piles["Deck"], False, 1)},
    'Super 17': {mill: (me.piles["Deck"], False, 2), draw: (me.piles["Deck"], False, 1)},
##    'Physical Mastery Uub': {mill: (me.piles["Deck"], False, 3)},
    'Endless Malice Android 17': {mill: (me.piles["Deck"], False, 3)},
    'Master Roshi': {mill: (me.piles["Deck"], False, 2), draw: (me.piles["Deck"], False, 1)},
    'SSB Vegeta, Testing His Limits': {mill: (me.piles["Deck"], False, 5)},
    'Black Masked Saiyan': {mill: (me.piles["Deck"], False, 3), draw: (me.piles["Deck"], False, 1)},
    'Powerthirst Black Masked Saiyan': {mill: (me.piles["Deck"], False, 3), draw: (me.piles["Deck"], False, 1)},
    'Vegeta, Returned from Darkness': {mill: (me.piles["Deck"], False, 5)},
    'Mega Focus Son Goku': {mill: (me.piles["Deck"], False, 3)},
    

    'Manipulating God Champa': {tutorTopComplex: (me.piles["Deck"], 7, 1, {'Character': ('Champa', 'e'),'Color': ('Red','e')})},
    'Calm-Hearted Vados': {tutorTopComplex: (me.piles["Deck"], 7, 1, {'Special Trait': ('Alien', 'e'),'Color': ('Red','e')})},
    'Kind Saiyan Son Goku': {tutorTopComplex: (me.piles["Deck"], 7, 1, {'Character': ('Son Goku', 'e'),'Color': ('Blue','e')})},
    'Bulma, God Tempter': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Character': ('Whis', 'e'),'Cost': (4,'le')})},
    'Mega Cannon Sigma, Natt': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Character': ('Bizu', 'e')})},
    'Mega Cannon Sigma, Bizu': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Character': ('Ribet', 'e')})},
    'Mega Cannon Sigma, Ribet': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Character': ('Nezi', 'e')})},
    'Indomitable Link Piccolo': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Character': ('Son Gohan: Adolescence', 'e'), 'Cost': (4, 'le')})},
    'Surprise Attack Majin Buu': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Character': ('Majin Buu', 'e'), 'Power': (25000, 'le')})},
    'Cabba, Universe Mediator': {tutorTopComplex: (me.piles["Deck"], 3, 1, {'Special Trait': ('Universe 6', 'i')})},
    'Bold Super Saiyan 2 Caulifla': {tutorTopComplex: (me.piles["Deck"], 7, 1, {'Special Trait': ('Universe 6', 'i'),'Power': (15000,'le')})},
    'Frost, The Tactician': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Character': ('Frost', 'e'),'Power': (20000,'le')})},
    'Ready to Fight Son Goku': {tutorTopComplex: (me.piles["Deck"], 3, 1, {'Special Trait': ('Universe 7', 'i')})},
    'Universe 9 Striker Roselle': {tutorTopComplex: (me.piles["Deck"], 3, 1, {'Special Trait': ('Universe 9', 'i')})},
    'Girl Warrior Brianne De Chateau': {tutorTopComplex: (me.piles["Deck"], 7, 1, {'Special Trait': ('Maiden Squadron', 'i')})},
    'Zarbuto, Maiden Attendant': {tutorTopComplex: (me.piles["Deck"], 3, 1, {'Special Trait': ('Universe 2', 'i')})},
    'Agony of Hell Frieza': {tutorTopComplex: (me.piles["Drop Zone"], 100, 1, {'Character': ('Frieza', 'i')})},
    'Hero Combination Tupper': {tutorTopComplex: (me.piles["Deck"], 3, 1, {'Special Trait': ('Universe 11', 'i')})},
    'Universe 7 Representative': {tutorTopComplex: (me.piles["Deck"], 7, 1, {'Special Trait': ('Universe 7', 'i')})},
    'Paragus, Controller of Monsters': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Name': ('Broly\'s Ring', 'i')})},
    'Broly, Dawn of the Rampage': {tutorTopComplex: (me.piles["Deck"], 7, 1, {'Character': ('Broly', 'i')})},    
    'Avenging Frieza': {tutorTopComplex: (me.piles["Deck"], 3, 1, {'Special Trait': ('Frieza', 'i'), 'Special Trait': ('Army', 'i')})},    
    'Leap to The Future Son Goten': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Character': ('Gotenks', 'e'),'Power': (25000,'le')})},
    'Leap to The Future Son Trunks': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Character': ('Gotenks', 'e'),'Power': (25000,'le')})},
    'Terrible Creator Android 20': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Name': ('Android', 'i')})},    
    'Hercule, Buus Assistant': {tutorTopComplex: (me.piles["Deck"], 7, 1, {'Character': ('Buu', 'i')})},
    'Universe 10 Supreme Kai Gowasu': {tutorTopComplex: (me.piles["Deck"], 3, 1, {'Special Trait': ('God', 'i')})},
    'Unified Spirit Son Goten': {tutorTopComplex: (me.piles["Deck"], 7, 1, {'Character': ('Trunks: Youth', 'i')})},
    'Implacable Trunks': {tutorTopComplex: (me.piles["Drop Zone"], 100, 1, {'Name': ('', 'i')})},
    'Pint-sized Warrior Son Goku': {tutorTopComplex: (me.piles["Deck"], 7, 1, {'Character': ('Son Goku: GT', 'e')})},
    'Shocking Future Son Goku': {tutorTopComplex: (me.piles["Deck"], 7, 1, {'Character': ('Son Goku: GT', 'e'), 'Power': (5000, 'le')})},
    'Universal Leader, Grand Supreme Kai': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Name': ('Supreme Kai', 'i'), 'Character': ('Grand Supreme Kai', 'ne')})},
    'Agent of Resurrection': {tutorTopComplex: (me.piles["Deck"], 3, 1, {'Character': ('Majin Buu', 'e')})},
    'Dr. Gero, Evils Inventor': {tutorTopComplex: (me.piles["Deck"], 3, 1, {'Special Trait': ('Android', 'i')})},
    'Trunks, Power Overseeing Time': {tutorTopComplex: (me.piles["Warp"], 100, 1, {'Type': ('Battle', 'i')})},
    'Lord of the Great Apes, King Vegeta': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Special Trait': ('Great Ape', 'i'), 'Cost': (5, 'le')})},
    'Power of Friendship Pan': {tutorTopComplex: (me.piles["Deck"], 5, 1, {'Character': ('GT', 'i'), 'Power': (15000, 'le')})},
    'Heroic Encounter Trunks': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Character': ('Tapion', 'i')})},
    'City Patrol Great Saiyaman 2': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Name': ('City Patrol Great Saiyaman', 'e')})},
    'Hidden Darkness Minotia': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Name': ('Hirudegarn, the Wanderer', 'i')})},
    'Kindhearted Namekian Dende': {tutorTopComplex: (me.piles["Deck"], 3, 1, {'Special Trait': ('Namekian', 'i')})},
    'Lord Slug, Returned to Form': {tutorTopComplex: (me.piles["Deck"], 5, 1, {'Special Trait': ('Slug\s Army', 'i'), 'Cost': (4, 'le')})},
    'Deadly Golden Great Ape Son Goku': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Special Trait': ('Goku\'s Lineage', 'i'), 'Name': ('Deadly Golden Great Ape Son Goku', 'ne')})},
    'Dynasty\'s Solace Chi-Chi': {tutorTopComplex: (me.piles["Deck"], 3, 1, {'Special Trait': ('Goku\s Lineage', 'i')})},
    'Successor of Hope': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Special Trait': ('Goku\'s Lineage', 'i'), 'Cost': (5, 'le'), 'Text': ('Swap', 'i')})},
    'Frigid Blast Putine': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Character': ('Demigra', 'i'), 'Cost': (4, 'le')})},
    'Determined Time Leaper Trunks': {tutorTopComplex: (me.piles["Deck"], 7, 1, {'Character': ('Trunks: Future', 'i')})},    
    
    'Time Patrol Trunks': {scry: (me.piles["Deck"], 2)},
    'Sensing Old Kai': {scry: (me.piles["Deck"], 3, 1, 'Name', 'Miraculous Comeback Ultimate Gohan', me.hand, True)},
    'Comrades Combined Son Goku': {scry: (me.piles["Deck"], 7, '', 'Character', 'Vegeta', me.hand, True)},
    'Scrambling Assault Son Goten': {scry: (me.piles["Deck"], 3)},
    'Son Goku, Prepping for Fusion': {scry: (me.piles["Deck"], 3, '', '', '', me.hand, True)},
    'Vegeta, Prepping for Fusion': {scry: (me.piles["Deck"], 3, '', '', '', me.hand, True)},
    'Saiyan Bloodline Son Goku': {scry: (me.piles["Deck"], 3, '', '', '', me.hand, True)},
    'Saiyan Bloodline Vegeta': {scry: (me.piles["Deck"], 3, '', '', '', me.hand, True)},

    
    'Energy Boost Beerus': {kill: (1, True)},
    'Indomitable Link Son Gohan': {kill: (1, True, me.piles["Drop Zone"], {'Cost': (4,'le')})},
    'King Piccolo, Lord of Terror': {kill: (1, True, me.piles["Drop Zone"], {'Cost': (5,'le')})},
    'Son Goten, Family of Justice': {kill: (1, True, me.piles["Drop Zone"], {'Cost': (2,'le')})},
    'Raging Attacker Vegeta': {kill: (1, True, me.piles["Drop Zone"], {'Cost': (4,'le')})},
    'Broly, the Unstoppable Horror': {kill: (1, True)},
    'Determined Super Saiyan Son Gohan': {kill: (1, True)},
    'Vegeta, The Proud Father': {kill: (1, True)},
    'Trio De Dangers Lavender': {kill: (1, True, me.piles["Drop Zone"], {'Cost': (4,'le')})},
    'Hermilla, The Sniper': {kill: (1, True, me.piles["Drop Zone"], {'Cost': (5,'le')})},
    'Trickster Ganos': {kill: (1, True, me.piles["Drop Zone"], {'Cost': (4,'le')})},
    'Secret Vitality Jiren': {kill: (2, True)},
    'Cyborg Warrior Nigrisshi': {kill: (1, True, me.piles["Drop Zone"], {'Cost': (4,'le')})},
    'Kami\'s Power Piccolo': {kill: (1, True)},
    'Limitless Energy Android 17': {kill: (1, True)},
    
##                'Intrepid Determination Bardock': kill,
##                'Full Power Vegeta': kill,
##                'Destructive Terror Champa': kill,
##                'Awakening Rage Son Goku': kill,
    'Vile Replication Cell': {token: (table, 0, 0, 'e043c8cb-cd4d-4a49-816f-bbf715bc57e4', 3), draw: (me.piles["Deck"], False, 2)},

    'Dragon Ball Seeker Sorbet': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Text': ('Dragon Ball', 'b')})},    

    'Ghost Attack Super Saiyan 3 Gotenks': {token: (table, 0, 0, 'e043c8cb-cd4d-4a49-816f-bbf715bc57e4', 3)},
    'Uncountable Many Cell Jr.': {token: (table, 0, 0, '0b5c0703-658c-4d83-871e-9f7b666f2a8d', 2)},
    'Super Ghost Kamikaze Attack': {token: (table, 0, 0, 'e043c8cb-cd4d-4a49-816f-bbf715bc57e4', 2)},
    'Chilled': {token: (table, 0, 0, 'e59dd1d5-3fc4-413d-abf3-e97de86f2ebb', 1)},
    'Chilled, Harbinger of Destruction': {token: (table, 0, 0, 'e59dd1d5-3fc4-413d-abf3-e97de86f2ebb', 1)},
    'Ghost Combo Gotenks': {token: (table, 0, 0, 'e043c8cb-cd4d-4a49-816f-bbf715bc57e4', 1)},
##    'Nightmare Scythe Goku Black': {token: (table, 0, 0, 'e043c8cb-cd4d-4a49-816f-bbf715bc57e4', 1)},
    'Space Pirate Chilled': {token: (table, 0, 0, 'e59dd1d5-3fc4-413d-abf3-e97de86f2ebb', 2), draw: (me.piles["Deck"], False, 1)},
##    'Head Honcho Medamatcha': {token: (table, 0, 0, 'e043c8cb-cd4d-4a49-816f-bbf715bc57e4', 1)},

    'Planet M-2': {draw: (me.piles["Deck"], False, 1)}, 
    'Triple Union Super Sigma': {draw: (me.piles["Deck"], False, 2)},
    'Meta-Rilldo, Form Perfected': {draw: (me.piles["Deck"], False, 2)},
    'Encroaching Terror Android 19': {draw: (me.piles["Deck"], False, 1)},    
    'Planet Vegeta': {tutorTopComplex: (me.piles["Deck"], 100, 1, {'Special Trait': ('Saiyan', 'i'),'Cost': (4,'le')})},
    
    'Whis,the Resting Attendant': {topCardEnergy: (me.piles["Deck"], 1)}
}


